# We have two kinds of storage classes under microk8s' hostpath provisioner.
# One will be used for workloads that require ephemeral storage with reclaim policy "Delete". This is the default storage class.
# Another one will host applications that require persistent storage like Plex.

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage-retain
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /media/k8s-data
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage-temp
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /media/k8s-data
volumeBindingMode: WaitForFirstConsumer