apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
spec:
  storageClassName: "local-storage-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi