apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-movies-pvc
spec:
  storageClassName: "local-storage-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-series-pvc
spec:
  storageClassName: "local-storage-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-pvc
spec:
  storageClassName: "local-storage-retain"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi