apiVersion: v1
kind: Service
metadata:
  name: unbound-dns
  labels:
    app: unbound-dns
spec:
  type: NodePort
  ports:
    - name: dns-tcp
      port: 53
      nodePort: 53
      protocol: TCP
      targetPort: dns-tcp
    - name: dns-udp
      port: 53
      nodePort: 53
      protocol: UDP
      targetPort: dns-udp
  selector:
    app: unbound-dns